name: DevSecOps CI/CD Pipeline
on:
  push:
    branches:
      - develop

jobs:
  
  SAST:
    runs-on: ubuntu-latest
    name: Static Application Security Testing
    steps:   
    
      - name: Git Clone
        uses: actions/checkout@v4
      
        
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      
  SCA:
    needs: SAST
    name: Software Composition Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Git Clone
        uses: actions/checkout@v4
        
      - name: Build
        run: |
          echo "Build the project"

      - name: Dependency Check
        run: |
          echo "Run dependency check"
                    
  Docker-build:
    name: Build Docker Image
    needs: 
      - SAST
      - SCA
    runs-on: ubuntu-latest
    steps:
    
      - name: Docker Auth
        run: |
          echo "Docker login"

      - name: Docker Config
        uses: docker/setup-buildx-action@v3
      
      - name: Construccion Imagen
        run: | 
          #docker build -t clagosu/ms-aumento-voto:latest .
          echo "Docker build"

  Container-Analysis:
    name: Container Vulnerability Analysis
    needs: Docker-build
    runs-on: ubuntu-latest
    steps:
    
      - name: Vulnerability Analysis
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: 'andres-dcic/demo-cicd-devsecops:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          
  Docker-push:
    needs: 
      - Container-Analysis
    runs-on: ubuntu-latest
    steps:
    
      - name: Docker push
        run: |
          echo "Docker push"