on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main
jobs:
  sonarcloud-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Run SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.sonar }}
        run: |
          npm install -g sonar-scanner
          sonar-scanner \
            -Dsonar.projectKey=andres-dcic_demo-cicd-devsecops \
            -Dsonar.organization=andres-dcic \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.sonar }}
      
      - name: Install Snyk
        run: npm install -g snyk

      - name: Auth with Snyk
        run: snyk auth ${{ secrets.snyk }}

      - name: Snyk Open Source Scan (dependencies)
        run: snyk test --file=package.json --severity-threshold=high || echo "⚠️ Snyk found issues, but pipeline continues"


      - name: Snyk Monitor (upload results to dashboard)
        run: snyk monitor --file=package.json  

      
